//! Stamp Dark-Blood branding from the crate version so icons/badges never drift.
//!
//! Single source of truth: Cargo.toml package.version → env CARGO_PKG_VERSION.
//! Regenerates assets/generated/* on every build. UI and tests assert match.

use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    let version = env::var("CARGO_PKG_VERSION").expect("CARGO_PKG_VERSION");
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let gen_dir = manifest_dir.join("assets").join("generated");
    let _ = fs::create_dir_all(&gen_dir);

    // Git short rev (best-effort) so banners prove which source the binary was built from.
    // Rerun when HEAD moves so Launch-Perci rebuilds pick up the new identity automatically.
    let git_head = manifest_dir.join(".git").join("HEAD");
    println!("cargo:rerun-if-changed={}", git_head.display());
    let rev = git_short_rev(&manifest_dir);
    let dirty = git_dirty(&manifest_dir);
    let build_id = if rev.is_empty() {
        version.clone()
    } else if dirty {
        format!("{version}+{rev}-dirty")
    } else {
        format!("{version}+{rev}")
    };

    // Always rewrite VERSION stamp (semver + optional +rev).
    let version_path = gen_dir.join("VERSION");
    fs::write(&version_path, format!("{build_id}\n")).expect("write VERSION");
    fs::write(gen_dir.join("BUILD_ID"), format!("{build_id}\n")).expect("write BUILD_ID");

    // Versioned badge SVG (exact text via code — never hand-edited).
    let badge = render_badge_svg(&version);
    fs::write(gen_dir.join("perci-darkblood-badge.svg"), badge).expect("write badge svg");

    // Mirror into OUT_DIR for include_str! stability if workspace is cleaned.
    fs::write(out_dir.join("PERCI_BRAND_VERSION"), format!("{version}\n"))
        .expect("write OUT version");
    fs::write(out_dir.join("PERCI_BUILD_ID"), format!("{build_id}\n")).expect("write OUT build id");
    fs::write(
        out_dir.join("perci-darkblood-badge.svg"),
        render_badge_svg(&version),
    )
    .expect("write OUT badge");

    // Human-readable brand manifest.
    let rev_json = if rev.is_empty() {
        "null".to_owned()
    } else {
        format!("\"{rev}\"")
    };
    let manifest = format!(
        "{{\n  \"name\": \"Perci\",\n  \"theme\": \"dark-blood\",\n  \"version\": \"{version}\",\n  \"build_id\": \"{build_id}\",\n  \"git_rev\": {rev_json},\n  \"mark\": \"assets/icons/perci-darkblood-mark.svg\",\n  \"badge\": \"assets/generated/perci-darkblood-badge.svg\",\n  \"mark_raster\": \"assets/icons/perci-darkblood-mark.jpg\",\n  \"mark_ico\": \"assets/icons/perci-darkblood.ico\",\n  \"source_of_truth\": \"Cargo.toml package.version + git HEAD\",\n  \"policy\": \"Never hand-edit generated badge version; rebuild after bumping Cargo.toml. Launch-Perci always cargo-builds live target and kills stale daemons.\"\n}}\n"
    );
    fs::write(gen_dir.join("brand-manifest.json"), &manifest).expect("write brand manifest");

    println!("cargo:rerun-if-changed=Cargo.toml");
    println!("cargo:rerun-if-changed=assets/icons/perci-darkblood-mark.svg");
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rustc-env=PERCI_BRAND_VERSION={version}");
    println!("cargo:rustc-env=PERCI_BUILD_ID={build_id}");
}

fn git_short_rev(repo: &std::path::Path) -> String {
    let output = std::process::Command::new("git")
        .args(["rev-parse", "--short=8", "HEAD"])
        .current_dir(repo)
        .output();
    match output {
        Ok(o) if o.status.success() => String::from_utf8_lossy(&o.stdout).trim().to_owned(),
        _ => String::new(),
    }
}

fn git_dirty(repo: &std::path::Path) -> bool {
    let output = std::process::Command::new("git")
        .args(["status", "--porcelain"])
        .current_dir(repo)
        .output();
    match output {
        Ok(o) if o.status.success() => !String::from_utf8_lossy(&o.stdout).trim().is_empty(),
        _ => false,
    }
}

fn render_badge_svg(version: &str) -> String {
    // Escape XML text (version is semver digits/dots only, but stay safe).
    let v = version
        .replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;");
    format!(
        r##"<?xml version="1.0" encoding="UTF-8"?>
<!-- AUTO-GENERATED by build.rs — do not edit. Version from Cargo.toml. -->
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 560" role="img" aria-label="Perci Dark Blood v{v}">
  <defs>
    <radialGradient id="void" cx="50%" cy="42%" r="62%">
      <stop offset="0%" stop-color="#1a0a0c"/>
      <stop offset="100%" stop-color="#050203"/>
    </radialGradient>
    <linearGradient id="blood" x1="0%" y1="0%" x2="100%" y2="100%">
      <stop offset="0%" stop-color="#FF334F"/>
      <stop offset="55%" stop-color="#B11226"/>
      <stop offset="100%" stop-color="#6B0A14"/>
    </linearGradient>
  </defs>
  <rect width="512" height="560" rx="48" fill="#050203"/>
  <circle cx="256" cy="236" r="200" fill="url(#void)" stroke="#3a1018" stroke-width="6"/>
  <g stroke="#5c1824" stroke-width="1" opacity="0.5">
    <path d="M120 160 H392 M120 210 H392 M120 260 H392 M120 310 H392"/>
    <path d="M170 110 V360 M220 110 V360 M280 110 V360 M330 110 V360"/>
  </g>
  <path d="M256 96 L372 236 L256 376 L140 236 Z" fill="url(#blood)" stroke="#FF334F" stroke-width="8" stroke-linejoin="round"/>
  <path d="M256 150 L320 236 L256 260 L192 236 Z" fill="#FF334F" opacity="0.2"/>
  <path d="M256 348 C256 348 240 368 240 382 C240 392 247 398 256 398 C265 398 272 392 272 382 C272 368 256 348 256 348 Z" fill="#B11226" stroke="#FF334F" stroke-width="2"/>
  <text x="256" y="500" text-anchor="middle" font-family="Segoe UI, Helvetica, Arial, sans-serif" font-size="36" font-weight="700" fill="#E8D8D8">PERCI</text>
  <text x="256" y="536" text-anchor="middle" font-family="Segoe UI, Helvetica, Arial, sans-serif" font-size="28" font-weight="600" fill="#FF334F">v{v}</text>
</svg>
"##
    )
}
